BTW cerner_2^5_2019
BTW Simple recursion in LOLCODE
HAI 1.3
    HOW IZ I FACTORIAL YR N
        BOTH SAEM N AN 0
        O RLY?
            YA RLY, FOUND YR 1
        NO WAI
            FOUND YR PRODUKT OF N AN I IZ FACTORIAL YR DIFF OF N AN 1 MKAY
        OIC
    IF U SAY SO

    I HAS A INPUT
    VISIBLE "GIMMEH FACTORIAL OF?"
    GIMMEH INPUT
    VISIBLE I IZ FACTORIAL YR INPUT MKAY
KTHXBYE